### ISSUE TITLE
Rstudio

### ISSUE THREAD

**Issue by Montaner32** [maestria-geotel-201902/unidad-0-asignacion-1-asig-conrstudio-issues-Montaner32#2]
Buenas Noches Profesor,

Le escribo para que me haga la habilitación al servidor de RStudio manejado por usted....

Gracias de antemano...
@geofis

**Comment by geofis** [comment]
@Montaner32 al parecer, no había hecho seguimiento de este *issue*. Ya tienes cuenta de acceso a RStudio, así que cierro este issue. Sobre el *commit* que hiciste anoche, revisa el comentario que hice en él.
